version: '3'
services:
    frontend:
        build: 
            context: ./frontend
        container_name: frontend
        ports:
            - '3000:3000'
        restart: always
    service1:
        build: 
            context: ./service1
        container_name: service1
        ports:
            - '5000:5000'
        restart: always
    service2:
        build: 
            context: ./service2
        container_name: service2
        ports:
            - '5001:5001'
        restart: always
    service3:
        build: 
            context: ./service3
        container_name: service3
        ports:
            - '5002:5002'
        restart: always
    service4:
        build: 
            context: ./service4
        container_name: service4
        ports:
            - '5003:5003'
        restart: always