apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  labels:
    app: k8s-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31118
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31119
    - port: 5001
      protocol: TCP
      targetPort: 5001
      nodePort: 31120
    - port: 5002
      protocol: TCP
      targetPort: 5002
      nodePort: 31121
    - port: 5003
      protocol: TCP
      targetPort: 5003
      nodePort: 31122
    - port: 5004
      protocol: TCP
      targetPort: 5004
      nodePort: 31123
  selector:
    app: k8s-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  labels:
   app: k8s-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo-frontend
        image: kantlove/k8s-demo-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
      - name: k8s-demo-service1
        image: kantlove/k8s-demo-service1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
      - name: k8s-demo-service2
        image: kantlove/k8s-demo-service2
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          protocol: TCP
      - name: k8s-demo-gateway
        image: kantlove/k8s-demo-gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
          protocol: TCP
      - name: k8s-demo-service3
        image: kantlove/k8s-demo-service3
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
          protocol: TCP
      - name: k8s-demo-service4
        image: kantlove/k8s-demo-service4
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
          protocol: TCP